# Generated by Django 2.0 on 2018-06-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_log', '0003_auto_20171002_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplelog',
            name='object_repr',
            field=models.TextField(blank=True, verbose_name='object repr'),
        ),
        migrations.AlterField(
            model_name='simplelog',
            name='user_repr',
            field=models.TextField(blank=True, verbose_name='user repr'),
        ),
    ]
