# Generated by Django 3.1.5 on 2021-01-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_log', '0004_auto_20180614_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplelog',
            name='object_id',
            field=models.TextField(blank=True, default='', verbose_name='object id'),
            preserve_default=False,
        ),
    ]
