name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      POSTGRES_DB: simple_log
      POSTGRES_PORT: 5432
    strategy:
      matrix:
        - name: Python 3.6 / Django 3.2
          python_version: "3.6"
          tox_env: py36-dj32

        - name: Python 3.7 / Django 3.2
          python_version: "3.7"
          tox_env: py37-dj32

        - name: Python 3.8 / Django 3.2
          python_version: "3.8"
          tox_env: py38-dj32

        - name: Python 3.9 / Django 3.2
          python_version: "3.9"
          tox_env: py39-dj32

        - name: Python 3.10 / Django 3.2
          python_version: "3.10"
          tox_env: py310-dj32

        - name: Python 3.8 / Django 4.0
          python_version: "3.8"
          tox_env: py38-dj40

        - name: Python 3.9 / Django 4.0
          python_version: "3.9"
          tox_env: py39-dj40

        - name: Python 3.10 / Django 4.0
          python_version: "3.10"
          tox_env: py310-dj40

        - name: Python 3.8 / Django 4.1
          python_version: "3.8"
          tox_env: py38-dj41

        - name: Python 3.9 / Django 4.1
          python_version: "3.9"
          tox_env: py39-dj41

        - name: Python 3.10 / Django 4.1
          python_version: "3.10"
          tox_env: py310-dj41

        - name: Python 3.10 / Django 4.1
          python_version: "3.10"
          tox_env: py310-dj41

        - name: Python 3.11 / Django 4.1
          python_version: "3.11"
          tox_env: py311-dj41

        - name: Python 3.8 / Django master
          python_version: "3.8"
          tox_env: py38-djmaster

        - name: Python 3.9 / Django master
          python_version: "3.9"
          tox_env: py39-djmaster

        - name: Python 3.10 / Django master
          python_version: "3.10"
          tox_env: py310-djmaster

        - name: Python 3.10 / Django master
          python_version: "3.10"
          tox_env: py310-djmaster

        - name: Python 3.11 / Django master
          python_version: "3.11"
          tox_env: py311-djmaster

        - name: Linters
          python_version: "3.11"
          tox_env: linters
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_PORT: ${{ env.POSTGRES_PORT }}
        run: |
          tox
