name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: simple_log
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Python 3.6 / Django 3.2
            python-version: "3.6"
            tox-env: py36-dj32

          - name: Python 3.7 / Django 3.2
            python-version: "3.7"
            tox-env: py37-dj32

          - name: Python 3.8 / Django 3.2
            python-version: "3.8"
            tox-env: py38-dj32

          - name: Python 3.9 / Django 3.2
            python-version: "3.9"
            tox-env: py39-dj32

          - name: Python 3.10 / Django 3.2
            python-version: "3.10"
            tox-env: py310-dj32

          - name: Python 3.8 / Django 4.1
            python-version: "3.8"
            tox-env: py38-dj41

          - name: Python 3.9 / Django 4.1
            python-version: "3.9"
            tox-env: py39-dj41

          - name: Python 3.10 / Django 4.1
            python-version: "3.10"
            tox-env: py310-dj41

          - name: Python 3.11 / Django 4.1
            python-version: "3.11"
            tox-env: py311-dj41

          - name: Python 3.8 / Django 4.2
            python-version: "3.8"
            tox-env: py38-dj42

          - name: Python 3.9 / Django 4.2
            python-version: "3.9"
            tox-env: py39-dj42

          - name: Python 3.10 / Django 4.2
            python-version: "3.10"
            tox-env: py310-dj42

          - name: Python 3.11 / Django 4.2
            python-version: "3.11"
            tox-env: py311-dj42

          - name: Python 3.8 / Django master
            python-version: "3.8"
            tox-env: py38-djmaster

          - name: Python 3.9 / Django master
            python-version: "3.9"
            tox-env: py39-djmaster

          - name: Python 3.10 / Django master
            python-version: "3.10"
            tox-env: py310-djmaster

          - name: Python 3.10 / Django master
            python-version: "3.10"
            tox-env: py310-djmaster

          - name: Python 3.11 / Django master
            python-version: "3.11"
            tox-env: py311-djmaster


    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: tox -e ${{ matrix.tox-env }}